name: Argos CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          # A minimal fetch-depth of 2 is required
          # to automatically detect branch in @argos-ci/cli
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Tests / Screenshots
        run: yarn test

      - name: Upload screenshots to argos-ci.com
        continue-on-error: true
        run: npx @argos-ci/cli upload ./screenshots
